# Generated by Django 5.1.2 on 2025-04-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.TextField()),
                ('ownerphone', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('flat', 'Flat'), ('house', 'House'), ('pg', 'PG')], max_length=20)),
                ('bhk_type', models.CharField(choices=[('1RK', '1 RK'), ('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('4BHK', '4 BHK')], default='1RK', max_length=10)),
                ('preferred_tenants', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('couples', 'Couples'), ('family', 'Family'), ('mixed', 'Mixed'), ('unmarried_couples', 'Unmarried Couples')], max_length=20)),
                ('looking_for', models.CharField(choices=[('students', 'Students'), ('working_professionals', 'Working Professionals'), ('family', 'Family')], max_length=30)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('furnishing', models.CharField(choices=[('semi-furnished', 'Semi-Furnished'), ('fully-furnished', 'Fully-Furnished'), ('unfurnished', 'Unfurnished')], max_length=50)),
                ('available_from', models.DateField()),
            ],
        ),
    ]
